product/consul.go
It seems that we were recently unable to clone the consul repo in our E2E tests under the default 1 minute timeout:
```
2021/11/10 22:11:00 git_revision.go:123: cloning consul repository from https://github.com/hashicorp/consul.git to /tmp/hc-install-build-consul1492782617 (timeout: 1m0s)
git_revision_test.go:58: unable to clone consul from "https://github.com/hashicorp/consul.git": context deadline exceeded
--- FAIL: TestGitRevision_consul (61.65s)
```
=> product: bump consul clone timeout

installer.go
This was just an oversight on my part in how multierror is supposed to be used.
When no error is appended, the variable remains `nil` and therefore attempting to access any of its fields will crash.
=> fix: avoid crash in installer

build/git_revision.go, product/consul.go
After seeing that Terraform already takes around 30-40 seconds on average to clone and close to 5 mins to build in GHA environment I decided to just raise the default timeouts.
https://github.com/hashicorp/hc-install/runs/4177083536?check_suite_focus=true#step:5:18
=> product: revise default clone & build timeouts

installer.go, installer_test.go
Closes https://github.com/hashicorp/hc-install/issues/25
The two main methods (`Ensure` and `Install`) have inconsistent behaviour in the sense that `Install` doesn't perform validation or track installed files such that they can be removed.
This PR aligns both methods.
While reading this code I also realized that we make (somewhat unconscious) assumption that the state (removable files) only survives until the next `Ensure` or `Install` call, so the user can't really call both or one of those repeatedly, unless they also always call `Remove` before. I created a separate issue to track that though: https://github.com/hashicorp/hc-install/issues/35
=> installer: align Install with Ensure & test it

fs/any_version.go, fs/fs_unix_test.go, fs/fs_windows_test.go
Closes https://github.com/hashicorp/hc-install/issues/39
=> fs.AnyVersion: Introduce ExactBinPath

fs/any_version.go, fs/any_version_test.go
Previously, if `Product` was specified, but not `ExactBinPath`, the following error was returned:
```
1 error occurred:
* expected ExactBinPath ("") to be an absolute path
```
=> fs: Fixes and unit testing for (AnyVersion).Validate()

fs/fs_test.go, fs/fs_unix_test.go, fs/fs_windows_test.go, installer_test.go, internal/testutil/temp_file.go
Validators should be tested either way separately, but `fs.AnyVersion` seems like a common enough use case that it's worth testing it also from the top-level API perspective.
The failing test is being fixed in #42
=> installer: Add top-level E2E test for fs.AnyVersion

fs/fs_test.go, fs/fs_unix_test.go, fs/fs_windows_test.go
Reference: https://pkg.go.dev/testing#T.Setenv
Added in Go 1.17. It will automatically reset the environment variable after each test.
=> fs: Replace os.Setenv() usage in testing with (testing.T).Setenv()

internal/releasesjson/checksum_downloader.go, internal/releasesjson/downloader.go
I spent time wondering why does checksum calculation take a while until I realized what happened.
```
2022/02/03 16:35:05 will install into dir at /var/folders/9w/pddq2x656j76vxvsbhcs4nwr0000gq/T/TestRepro2318612991/001/hcinstall
2022/02/03 16:35:05 requesting versions from https://releases.hashicorp.com/terraform/index.json
2022/02/03 16:35:05 received 200 OK
2022/02/03 16:35:05 downloading signature from https://releases.hashicorp.com/terraform/1.1.5/terraform_1.1.5_SHA256SUMS.72D7468F.sig
2022/02/03 16:35:05 downloading checksums from https://releases.hashicorp.com/terraform/1.1.5/terraform_1.1.5_SHA256SUMS
2022/02/03 16:35:05 checksum signature is valid
2022/02/03 16:35:05 downloading archive from https://releases.hashicorp.com/terraform/1.1.5/terraform_1.1.5_darwin_arm64.zip …
```
=> use Response.ContentLength & clarify log messages

.github/workflows/test.yml
This is to address the recent timeout:
https://github.com/hashicorp/hc-install/runs/5285804883?check_suite_focus=true#step:5:337
The test which varies the most is apparently _building_ - effectively `go build` on macOS. I'm unsure why that is, given that this only depends on the local CPU/memory (not network) - it could be some hardware issues on GitHub's side 🤔 
`TestGitRevision_consul` took `744.15s` last time but also `415.35s` before.
https://github.com/hashicorp/hc-install/runs/5285804883?check_suite_focus=true#step:5:57
=> ci: bump timeout for E2E tests

internal/releasesjson/releases.go, product/consul.go
Update the content-type checks to include the type returned from the releases api.
*Edit*: Also set Go version to 1.18 when building Consul from source. 
Closes #56 
Signed-off-by: Scott Macfarlane <smacfarlane@hashicorp.com>
=> Support releases-api returned content-type

build/git_revision.go
Terraform builds in particular started timing out recently in tfexec nightly tests.
https://app.circleci.com/pipelines/github/hashicorp/terraform-exec/1700/workflows/32189069-fab5-4884-bff7-6730fe6f625b/jobs/19137/steps
https://app.circleci.com/pipelines/github/hashicorp/terraform-exec/1695/workflows/a545d643-0365-44b0-ab87-d154936a9098/jobs/19097
The original 2min timeout is quite conservative IMO, and 5mins won't do much harm. The main purpose of these timeouts is to avoid waiting forever when there's network problems anyway.
=> build: bump default clone timeout from 2 to 5 mins

internal/releasesjson/checksum_downloader.go, internal/releasesjson/downloader.go, internal/releasesjson/releases.go, product/vault.go
The `Install` method (e.g. `(*releases.ExactVersion).Install`) takes a context, then calls `GetProductVersion` and `DownloadAndUnpack`, however, all http requests done within these functions do not propagate the context. This PR allows for the context to propagate.
=> installer: Allow context propagation to reach http requests

.github/workflows/test.yml
This is to address a recent test failure in https://github.com/hashicorp/hc-install/actions/runs/3439290334/jobs/5776891907#step:5:80
=> ci: bump workflow timeouts

.github/workflows/nightly-tests.yaml
Depends on #76 
Closes #41 
We could/should also probably bump Go used in CI and for development (per `.go-version`) but I left that for a separate PR.
=> ci: run E2E tests nightly

.github/dependabot.yml, .github/workflows/nightly-tests.yaml, .github/workflows/test.yml
This is to address the following warnings related to Node version:
https://github.com/hashicorp/hc-install/actions/runs/3487367151
=> ci: bump actions versions & enable dependabot updates

.github/workflows/nightly-tests.yaml
> Invalid workflow file
> The workflow is not valid. .github/workflows/nightly-tests.yaml (Line: 9, Col: 3): The workflow must contain at least one job with no dependencies.
=> ci: fix nightly GHA workflow

.github/workflows/nightly-tests.yaml, .github/workflows/test.yml
This uncovers the bug, which is being fixed as part of https://github.com/hashicorp/hc-install/pull/85
The reason tests are passing on 1.19 is because we don't install Go (as it already matches the requirement).
=> ci: Run tests on Go 1.18 & 1.19

build/git_revision.go, internal/build/install_go_version.go
Depends on https://github.com/hashicorp/hc-install/pull/86
--- 
On Go 1.18+, if we need to install Go, the installation results in the following error message
```
error installing terraform "gitref:refs/heads/main": unable to download Go 1.19.4: exec: "go1.19.4": executable file not found in $PATH
```
This is because we use `go get` to install Go, and since 1.18, the preferred methods is `go install`, `go get` no longer installs stuff: https://go.dev/doc/go-get-install-deprecation
This was discovered in https://github.com/hashicorp/terraform-exec/actions/runs/3873052889/jobs/6602632108#step:8:22
I'm on the edge of whether this needs to be tested, since it involves a lot of external calls.
--- 
This did not come up earlier because `terraform-exec` E2E nightly tests always ran on Go < 1.18.
=> internal/build: Fix installation of some Go versions

.github/workflows/test.yml
This is to address the oddly ambiguous titles as shown on this screenshot.
=> ci: Add OS name to test job titles

internal/releasesjson/downloader.go
As reported by CodeQL scanner, the code in question is potentially vulnerable to path traversal, i.e. reading files outside of expected path. However, in the context of `hc-install` we generally trust the source ZIP files as hosted on `releases.hashicorp.com`, since HashiCorp produces all of them anyway.
That said, there's nothing wrong with defence in depth.
- Snyk: [Zip Slip Vulnerability](https://snyk.io/research/zip-slip-vulnerability).
- OWASP: [Path Traversal](https://owasp.org/www-community/attacks/Path_Traversal).
- Common Weakness Enumeration: [CWE-22](https://cwe.mitre.org/data/definitions/22.html).
=> internal/releasesjson: Prevent path traversal

.github/workflows/nightly-tests.yaml, build/git_revision.go
In the last E2E nightly test run, we exceeded the 10m timeout for building `terraform` and `consul`. This may be an anomaly on GitHub's/Azure side inside the runner, making things slower than usual.
However, the E2E tests generally aren't supposed to measure the time, but rather whether at all we can successfully build the products. Therefore there is no benefit in keeping the timeouts too low.
=> build+ci: Bump default timeouts for building

version/version.go
Whenever a file is edited via GitHub UI, it seems impossible to avoid the trailing newline and `go-version` is (for better or worse) sensitive to that newline.
The second commit also ensures that any invalid version will cause panic earlier, on import of the `version` package, rather than on use of `Version()` function.
=> version: Trim spaces (newlines) from VERSION file

fs/fs_test.go
This is to help us get to the bottom of the flaky test, which sometimes fails on Windows:
https://github.com/hashicorp/hc-install/actions/runs/4074372806/jobs/7019467478#step:5:162
I wasn't able to reproduce this in a Windows VM unfortunately.
=> fs: Set logger in Version test

.github/workflows/build.yml
We learnt the hard way [elsewhere](https://github.com/hashicorp/vscode-terraform/issues/1346) that `go build` builds dynamically linked (CGO) binaries by default, at least when it's being built on the same target OS/arch (in our case linux/amd64).
This ensures that we build the `hc-install` CLI still as static binary without CGO.
=> ci: Disable CGO for CLI Linux builds

.github/workflows/test.yml
This is a follow-up to https://github.com/hashicorp/hc-install/pull/106 to ensure we don't introduce new files with missing copyright headers and keep the repository compliant.
=> ci: Add PR test for copyright headers

internal/releasesjson/checksum_downloader.go, internal/releasesjson/downloader.go
Do not store the entire release in memory, and instead stream the download through the checksum and file simultaneously. This change will significantly help our test performance over at [coder/coder](https://github.com/coder/coder).
=> Optimize checksum verification

internal/testutil/test_server.go, releases/releases_test.go
This enables us to accurately measure the impact of https://github.com/hashicorp/hc-install/pull/132 (with vs without patch).
We could add the benchmark there, but with the PR made from a `main` branch it makes it difficult for me to contribute back to that PR directly, so I'm raising a separate PR.
```sh
go test ./releases -bench=BenchmarkExactVersion -benchmem -run=^#
```
```
goos: darwin
goarch: arm64
pkg: github.com/hashicorp/hc-install/releases
BenchmarkExactVersion-10    	      31	  37298613 ns/op	 8111621 B/op	    6950 allocs/op
PASS
ok  	github.com/hashicorp/hc-install/releases	2.250s
```
=> releases: Add benchmark for ExectVersion.Install()

build/git_revision.go
This is to address recent test failures where it seems impossible to build vault within the existing 15 min limit.
https://github.com/hashicorp/hc-install/actions/runs/5952076475/job/16143254859#step:5:82
=> build: bump `BuildTimeout` from `15` to `25 mins`

README.md, checkpoint/latest_version.go, installer_examples_test.go, installer_test.go, internal/releasesjson/downloader.go, internal/releasesjson/releases.go, internal/releasesjson/releases_test.go, releases/enterprise.go, releases/exact_version.go, releases/exact_version_test.go, releases/latest_version.go, releases/latest_version_test.go, releases/versions.go, releases/versions_test.go
This pull request allows the installation of enterprise versions by supplying an `Enterprise bool` flag and an optional `EnterpriseMeta string` field as suggested in https://github.com/hashicorp/hc-install/issues/15#issuecomment-881566106.
---
According to #15 and #16, the ability to download enterprise versions was removed from the public release of this library. It seems this decision was likely made to prevent users from accidentally installing Enterprise versions.  However, there are some valid cases folks have the need to automate the downloading of Enterprise versions:
- [Automated testing of the Consul API Gateway project against the latest Consul Enterprise binaries](https://github.com/hashicorp/hc-install/issues/15#issuecomment-962244883)
- Preinstalling the latest enterprise …
=> releases: support enterprise versions

releases/latest_version.go, releases/latest_version_test.go
This uses the version constraint passed into the `LatestVersion` struct to ensure the constraints are checked against the returned versions.
=> `LatestVersion` - use version `Constraints` passed in

.github/workflows/release.yml, docs/CONTRIBUTING.md
Releasing currently requires a number of additional steps outside of GitHub. For a simple project with simple release pipeline such as this one, there is no strong benefit to do multi-staged releasing, as some other bigger projects do.
Simplify release process by moving promotion steps into a GHA workflow.
=> ci: Automate releasing via bob

.github/workflows/release.yml
The `production` promotion is gated by human approval and AFAICT does not require `staging` to actually _finish_ the promotion before it gets to the approval point.
However, it still doesn't make much sense to even attempt to promote artifacts in staging to production before the promotion to staging has actually finished.
Admittedly this change won't actually fully achieve that, because as the command name suggests, it only _triggers_ the promotion (i.e. won't wait for completion of the promotion). We can at least avoid _triggering_ production promotion if the triggering the staging promotion fails though.
=> github/release: Ensure production workflow doesn't start before staging

internal/releasesjson/checksum_downloader.go, internal/releasesjson/product_version.go, internal/releasesjson/releases_test.go
I cannot think of a good reason why we had the `RawVersion` field there. It may have pre-dated `go-version`'s ability to unmarshal. Either way, this has led to a weird error message, as discovered by @bschaatsbergen in #191 
```
$ ./hc-install install -version 1.0.0 terraform
hc-install: will install terraform@1.0.0
failed to install terraform@1.0.0: no ZIP archive found for terraform <nil> darwin/arm64
```
```
$ go run ./cmd/hc-install install -version 1.0.0 terraform
hc-install: will install terraform@1.0.0
failed to install terraform@1.0.0: no ZIP archive found for terraform 1.0.0 darwin/arm64
exit status 1
```
=> releasesjson: Fix missing Version in unmarshaled response

README.md, docs/CONTRIBUTING.md
Lint Markdown using [markdownlint](https://github.com/DavidAnson/markdownlint)
Mostly whitespace fixes, but also [MD034 - No bare URLs](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md034.md)
=> Lint Markdown

fs/fs_unix.go
```
S1011: should replace loop with `dirs = append(dirs, extraDirs...)` (gosimple)
```
=> [chore] Fix minor lint issue

.github/workflows/build.yml
This is to satisfy requirements from Legal, similar to
- https://github.com/hashicorp/terraform/pull/34977
- https://github.com/hashicorp/nomad/pull/20345
Importantly, this does _not_ address the issue tracked under https://github.com/hashicorp/hc-install/issues/197 but just ensures that `hc-install` CLI tool in itself has its own license file packaged with it in the ZIP archive and in the Linux packages we distribute.
=> Ensure license file gets packaged along w/ the CLI binary

cmd/hc-install/cmd_install.go, internal/releasesjson/downloader.go, releases/exact_version.go, releases/latest_version.go, releases/releases_test.go
Some environments do not have access to `releases.hashicorp.com`.
This PR adds a `CustomURL` var to `LatestVersion` and `ExactVersion`
This can be used in environments where calls to https://releases.hashicorp.com/ are firewalled for example.
Naming/dir structure would need to be the same as the Hashicorp version. There would also need to be `index.json` files within both the Version dir (`<url>/terraform/<version>/index.json` - [example](https://releases.hashicorp.com/terraform/1.8.2/index.json)) and Product dir (`<url>/terraform/index.json` - [example](https://releases.hashicorp.com/terraform/index.json)) as `hc-install` parses these for it's usage.
Atlantis is currently debating using `hc-install`. It would work for "default URL" downloads, but Atlantis also supports downloads from …
=> Add support for custom download URLs

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml
This sets up Dependabot to manage version updates for HashiCorp-owned GitHub Actions; all other (third-party) version updates are already handled by HashiCorp's internal TSCCR tooling. TSCCR does not/cannot manage HashiCorp-owned Actions versioning which is why we need to bring in Dependabot to handle this component; see [this memo](https://hermes.hashicorp.services/document/151w0ldYS3Z3arAiSTRuFImV73VabC0rhZJPCv6fzl4Q) (internal HashiCorp link) for details.
This PR also pins all HashiCorp-owned Actions used in this repo to using SHA hashes which is considered a security best-practice these days. This will force Dependabot to continue with this convention, and it is smart enough to update the comment on each of these lines to let us know which is the actual version that's being used.
=> github: Set up Dependabot to manage HashiCorp-owned Actions versioning

.github/CODEOWNERS
Realized this repo was also missing a CODEOWNERS. Can/should there be anyone else on this list or is it really just the Core team? I see a couple of commits from bflad and from a couple of Nomad team engineers, but that's it.
=> github: Create CODEOWNERS

build/git_revision.go, build/git_revision_test.go, checkpoint/latest_version.go, checkpoint/latest_version_test.go, internal/releasesjson/downloader.go, releases/exact_version.go, releases/latest_version.go, releases/releases_test.go
Closes https://github.com/hashicorp/hc-install/issues/197
--- 
The implementation has a few (intentional) side effects which may be worth calling out here:
- We now treat all/any license files the same, be it Enterprise related files like `EULA.txt` or CE related files like `LICENSE.txt`. It keeps the implementation simple and I don't see harm in it.
- When building the product from source, we also now copy the license file on a best effort basis, reflecting that the file name may not match `LICENSE.txt` but more often just `LICENSE`. The assumption I'm making there is that over time, those files would be renamed to `LICENSE.txt` and no _renaming_ would happen as part of a release. Again though - it's just best-effort basis that seemed relatively low effort.
As the diff was growing larger …
=> Ensure license files are tracked during installation so they can be removed

internal/releasesjson/downloader.go, internal/releasesjson/downloader_test.go
Currently when constructing the archive URL for download, only `Scheme` and `Host` are considered. This meams any `Path` within the custom URL is not used when constructing the Archive URL.
closes https://github.com/runatlantis/atlantis/issues/4778
=> [fix] include custom url's "path" when creating Archive URL

internal/httpclient/httpclient.go, internal/releasesjson/checksum_downloader.go, internal/releasesjson/downloader.go, internal/releasesjson/releases.go
=> httpclient: Reuse existing configured logger

.github/workflows/nightly-tests.yaml, .github/workflows/test.yml
Fix https://github.com/hashicorp/hc-install/issues/244
Tested by running the nightly builds on this branch. All builds passed and the "free up space" step was skipped for non-macOS runners.
=> Nightly and PR builds: fix "no space left on device" on macOS runner

catalog-info.yaml
Includes basic metadata for registering hc-install as a library component in our internal Backstage installation. See DW-481.
=> Add a catalog-info.yaml file for Backstage

internal/releasesjson/downloader.go
As mentioned in https://github.com/hashicorp/hc-install/issues/145 we never reuse the archive and so it makes sense to *always* remove it rather then collect it for removal by end-user via `Remove()` method.
This in turn reduces disk space in situations where it is important (outside of disposable CI environments).
Closes https://github.com/hashicorp/hc-install/issues/145
=> releasesjson: Always remove unpacked archive

build/git_revision_test.go, product/packer.go, product/product.go
Closes https://github.com/hashicorp/hc-install/issues/4
We can always add more products but I added notes to the original issue next to major products to effectively shorten the list and pragmatically close that issue.
=> product: Add packer

product/consul.go, product/terraform.go
Closes https://github.com/hashicorp/hc-install/issues/23
Other products do not seem to have `version` JSON output.
Existing tests will exercise the new codepath, although admittedly the legacy part will not be exercised. The difficulty with testing it is that older versions of Terraform and Consul aren't available on some OS/platform combinations like darwin/arm64.
I think the lack of testing is ok for now, in part because we'll gain some more debugging capabilities as part of https://github.com/hashicorp/hc-install/issues/46 hopefully.
=> product: Use `version` json output (consul + terraform)
